mass_arm: [10,0,0,0,0,0,
           0,10,0,0,0,0,
           0,0,68.37,0,0,0,
           0,0,0,1,0,0,
           0,0,0,0,10,0,
           0,0,0,0,0,1]
damping_arm: [78,0,0,0,0,0,
              0,34.2,0,0,0,0,
              0,0,171.7,0,0,0,
              0,0,0,10,0,0,
              0,0,0,0,10,0,
              0,0,0,0,0,1]
stiffness_coupling: [0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0,
                     0,0,0,0,0,0]

base_link: "base_link"
end_link: "wrist_3_link"
# [position (x, y, z)  orientation (x, y, z, w)]

desired_pose:  [0.0,-0.8,0.40,       0.001, 0.99, 0.00, 0.001]

arm_max_vel: 20
arm_max_acc: 50
arm_max_ang_vel: 0.8
arm_max_ang_acc: 1.5

# Rotation admittance (1D per axis)
m_yaw: 1.0
d_yaw: 1.0
k_yaw: 0.0
m_pitch: 1.0
d_pitch: 10.0
k_pitch: 0.0

workspace_limits: [-0.80, 0.80, -1.4, -0.45, -0.183, 0.207, -0.50, 0.50, 0.05] # [x_min, x_max, y_min, y_max, z_min, z_max, phi_min, phi_max, margin]

# robot base height is 793mm from ground
# normal wheelchair seat height is 460mm from ground
# estimate the distance from seat to waist as 150mm
# min_Z_height(from base_link) should be (460 + 150) - 793 = -183mm = -0.183m
