delay_sec: 0.0    # [s]

behaviors:
  - name: knee1
    type: KneeBuckling
    impulse_force_y: 23.3 #46.7
    impulse_force_z: 274.9 #549.8
    impulse_duration: 0.30    # [s]
    b_fall_time: 0.2       # [s]

  - name: slide1
    type: SeatSliding
    slide_force_y: 30.0     # [N] (start form small value)
    duration: 2.0           # [s]